name: Go lint
on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'examples/**'
      - '**.md'
      - LICENSE
      - '**.svg'
      - '.github/workflows/image.yml'
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - '**.md'
      - LICENSE
      - README.md
      - '**.svg'
      - '.github/workflows/image.yml'
      - '*.md'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        run: make lint
