name: Go lint
on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'examples/**'
      - '**.md'
      - LICENSE
      - '**.svg'
      - '.github/workflows/image.yml'
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - '**.md'
      - LICENSE
      - README.md
      - '**.svg'
      - '.github/workflows/image.yml'
      - '*.md'

env:
  GO_VERSION: ~1.18
  GO_VERSION_WIN: ~1.18

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-pkg-cache: true
          only-new-issues: false
          skip-build-cache: true
          skip-go-installation: true
          args: --verbose
