# options for analysis running
run:
  timeout: 8m

  build-tags:
    - hack
  skip-dirs-use-default: false
  skip-files:
    - "zz_*"
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - revive
    - gofmt
    - goheader

linters-settings:
  golint:
    min-confidence: 0
  goheader:
    template-path: .go-header.txt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # https://github.com/denis-tingaikin/go-header/issues/18
    # This means that the header checks are ineffective for all files with build tags.
    - source: "^//go:build"
      linters:
        - goheader
