# options for analysis running
run:
  timeout: 8m

  skip-dirs-use-default: false
  skip-dirs:
    - pkg/helm
    - static
    - hack
    - embedded-bins
    - pkg/apis/k0s.k0sproject.io/clientset
  skip-files:
    - "zz_*"
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - revive
    - gofmt
    - goheader

linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: false
  golint:
    min-confidence: 0
  goheader:
    template-path: .go-header.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - source: "^//go:build"
      linters:
        - goheader
    # Ignore deprecations: They shouldn't break the CI. If this were the case,
    # it would be pointless to have them. There's no way in reporting them as
    # warnings without having a non-zero exit code.
    # https://github.com/golangci/golangci-lint/pull/3184#issuecomment-1235438429
    - linters:
        - staticcheck
      text: "^SA1019:"
