apiVersion: v1
kind: ServiceAccount
metadata:
  name: autopilot
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autopilot-role-workers
rules:
  - apiGroups: ["autopilot.k0sproject.io"]
    resources: ["plans"]
    verbs: ["list", "watch"]

  - apiGroups: ["autopilot.k0sproject.io"]
    resources: ["plans/status"]
    verbs: ["update"]

  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "patch", "update", "watch"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]

  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autopilot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autopilot-role-workers
subjects:
- kind: ServiceAccount
  name: autopilot
  namespace: kube-system
