name: Go lint
on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '**.md'
      - LICENSE
      - '**.svg'
      - '.github/workflows/docs.yml'
      - '.github/workflows/mkdocs-set-default-version.yml'
      - 'mkdocs.yml'
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '**.md'
      - LICENSE
      - README.md
      - '**.svg'
      - '.github/workflows/docs.yml'
      - '.github/workflows/mkdocs-set-default-version.yml'
      - 'mkdocs.yml'
      - '*.md'

env:
  GO_VERSION: ~1.17
  GO_VERSION_WIN: ~1.17

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go caches
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-lint-go-caches-${{ hashFiles('go.sum') }}
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/golangci-lint

      - name: Check go.mod/go.sum to be consistent
        run: go mod tidy && git diff --exit-code

      - name: codegen
        run: make codegen EMBEDDED_BINS_BUILDMODE=none

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          skip-cache: true
          only-new-issues: false
          args: --verbose
